folding-at-home-cpu:
    build: .
    environment:
        - USERNAME=toto
        - POWER=light
        # - PASSKEY=test
    ports:
        - "127.0.0.1:30000:36330"
    volumes:
        - "./volume:/var/lib/fahclient:z"